name: CI

on:
  - push

jobs:
  tests:
    name: Run CI
    runs-on: ubuntu-latest

    env:
      NOXSESSION: tests
      FORCE_COLOR: "1"
      PRE_COMMIT_COLOR: "always"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.12

      - name: Install UV
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dependencies
        run: |
          make install-dev-deps
      - name: Run CI
        run: |
          make ci
