name: Publish Docker image

on:
  push:
    tags:
      - "*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [amd64, arm64]
    runs-on: ubuntu-${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate image tags
        id: image-metadata
        uses: docker/metadata-action@v5.7.0
        with:
          flavor: latest=false
          images: |
            ${{env.REGISTRY}}/${{env.IMAGE_NAME}}-${{ matrix.platform }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest
            type=sha,format=long
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.repositoryUrl }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push platform-specific Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/${{ matrix.platform }}
          tags: ${{ steps.image-metadata.outputs.tags }}
          labels: ${{ steps.image-metadata.outputs.labels }}
          cache-from: |
            type=registry,ref=${{env.REGISTRY}}/${{env.IMAGE_NAME}}-${{ matrix.platform }}:${{ github.ref_name }}
            type=registry,ref=${{env.REGISTRY}}/${{env.IMAGE_NAME}}-${{ matrix.platform }}:main
          cache-to: type=inline,mode=max

  manifest:
    runs-on: ubuntu-arm64
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create multi-arch manifest
        run: |
          docker buildx imagetools create \
            -t ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{ github.ref_name }} \
            -t ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest \
            ${{env.REGISTRY}}/${{env.IMAGE_NAME}}-amd64:${{ github.ref_name }} \
            ${{env.REGISTRY}}/${{env.IMAGE_NAME}}-arm64:${{ github.ref_name }}
